version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8080:5000"

  db:
    image: mysql:5.7
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro